#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# build
pyinstaller app-server.spec

# include example apps
cp -r apps dist
