#!/usr/bin/env bash
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
set -e


cd "$ROOT_DIR"


# clean
find . -name __pycache__ -exec rm -rf {} +
rm -rf build
rm -rf dist/app-server
rm -rf dist/apps
